name: Supabase keep-alive

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  test_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Show that the cron job is running
        run: curl -s "https://supabase-cron-jobs.vercel.app/api/keep-alive"