name: Test Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  test_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Show that the cron job is running
        run: echo "The GitHub Actions cron job is running at $(date)"