name: Scheduled API Call

on:
  schedule:
- cron: '*/1 * * * *'
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call API
        run: |
          curl -X GET "https://supabase-cron-jobs.vercel.app/api/keep-alive"